### ISSUE TITLE
Cannot start app

### ISSUE THREAD

**Issue by znat** [litentry/litentry-app#69]
Hi there,
I am trying to install and run the app but when running `yarn start`I got:

```
events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: EMFILE: too many open files, watch
    at FSEvent.FSWatcher._handle.onchange (internal/fs/watchers.js:178:28)
Emitted 'error' event on NodeWatcher instance at:
    at NodeWatcher.checkedEmitError (/Users/nathanzylbersztejn/git/litentry-app/node_modules/sane/src/node_watcher.js:143:12)
    at FSWatcher.emit (events.js:315:20)
    at FSEvent.FSWatcher._handle.onchange (internal/fs/watchers.js:184:12) {
  errno: -24,
  syscall: 'watch',
  code: 'EMFILE',
  filename: null
}
```

Seems a common error with react-native, but I installed watchman (I'm on Mac Big Sur) restarted to make sure I had not a high number of open files open by other projects,...

Is it something you know about?
Thanks

**Comment by geastwood** [comment]
Which version of `watchman` do you have?

**Comment by geastwood** [comment]
Feel free to reopen.
